from sqlalchemy import Column, Integer, String, BigInteger, DateTime, TEXT, Date
from app.db.base_class import Base


class CarTraining(Base):
    __tablename__ = "car_training"

    id = Column(BigInteger, index=True, primary_key=True, autoincrement=True, comment='')
    reservation_id = Column(BigInteger, nullable=True, comment='')
    company_code = Column(String(13), nullable=True)
    store_code = Column(String(13), nullable=True)
    customer_code = Column(String(13), nullable=True)
    car_code = Column(String(13), nullable=True)
    last_name = Column(String(255), nullable=True)
    first_name = Column(String(255), nullable=True)
    last_name_kana = Column(String(255), nullable=True)
    first_name_kana = Column(String(255), nullable=True)
    birthday = Column(Date, nullable=True)
    phone_number = Column(String(255), nullable=True)
    cellphone_number = Column(String(255), nullable=True)
    car_maker = Column(String(255), nullable=True)
    car_type = Column(String(255), nullable=True)
    car_number = Column(String(255), nullable=True)
    car_registration_end_date = Column(Date, nullable=True)
    reservation_data_type = Column(String(255), nullable=True)
    reservation_menu = Column(String(255), nullable=True)
    reservation_datetime = Column(DateTime, nullable=True)
    reservation_datetime_to = Column(DateTime, nullable=True)
    reservation_classification = Column(String(13), nullable=True)
    store_name = Column(String(255), nullable=True)
    reservation_memo = Column(TEXT, nullable=True)
    reservation_substitute_car_hope = Column(String(13), nullable=True)
    attracting_status = Column(String(13), nullable=True)
    attracting_type = Column(String(13), nullable=True)
    attracting_registration_end_date = Column(Date, nullable=True)
    customer_staff_main_name = Column(String(255), nullable=True)
    staff_code_in_charge = Column(String(13), nullable=True)
    registered_source_type = Column(String(13), nullable=True)
    remarks_1 = Column(String(255), nullable=True)
    remarks_2 = Column(String(255), nullable=True)
    remarks_3 = Column(String(255), nullable=True)
    remarks_4 = Column(String(255), nullable=True)
    remarks_5 = Column(String(255), nullable=True)
    vip = Column(Integer, nullable=True)
    rank = Column(Integer, nullable=True)
    work_request_form_no = Column(String(20), nullable=True)
    work_request_form_name = Column(String(50), nullable=True)
    release_date = Column(Date, nullable=True)
    input_date = Column(Date, nullable=True)
    output_date = Column(Date, nullable=True)
    car_mileage = Column(Integer, nullable=True)
    car_mileage_inspection_datetime = Column(DateTime, nullable=True)
    chassis_number = Column(String(255), nullable=True)
    store_manager = Column(String(255), nullable=True)
    update_staff = Column(String(255), nullable=True)
    insert_staff = Column(String(255), nullable=True)
    representative_fax_number = Column(String(20), nullable=True)
    insert_id = Column(BigInteger, nullable=False)
    insert_at = Column(DateTime, nullable=False)
    update_id = Column(BigInteger, nullable=False)
    update_at = Column(DateTime, nullable=False)
    delete_id = Column(BigInteger, nullable=False)
    delete_at = Column(DateTime, nullable=False)
    delete_flag = Column(Integer, nullable=False)
