from sqlalchemy import Column, Integer, String, BigInteger, DateTime, Date
from app.db.base_class import Base


class Customer(Base):
    id = Column(BigInteger, primary_key=True, unique=True, autoincrement=True, comment="ID")
    company_code = Column(String(13), index=True, nullable=False, comment="企業コード")
    customer_code = Column(String(13), index=True, nullable=False, comment="顧客コード")
    carsId = Column(String(13), comment="carsId")
    private_business = Column(String(2), comment="個人/法人区分")
    face_photo = Column(String(13), comment="顔写真")
    external_system_type = Column(String(13), comment="外部システム区分")
    external_system_key1 = Column(String(255), comment="外部システムキー1")
    external_system_key2 = Column(String(255), comment="外部システムキー2")
    last_name = Column(String(255), comment="姓")
    first_name = Column(String(255), comment="名")
    last_name_kana = Column(String(255), comment="姓カナ")
    first_name_kana = Column(String(255), comment="名カナ")
    sex = Column(String(2), comment="性別")
    birthday = Column(DateTime, comment="生年月日")
    phone_number = Column(String(255), nullable=False, comment="電話番号")
    phone_number_other = Column(String(255), comment="電話番号（その他）")
    cellphone_number = Column(String(255), nullable=False, comment="携帯電話")
    email = Column(String(255), nullable=False, comment="メールアドレス")
    email2 = Column(String(255), comment="メールアドレス2")
    email3 = Column(String(255), comment="メールアドレス3")
    email4 = Column(String(255), comment="メールアドレス4")
    email5 = Column(String(255), comment="メールアドレス5")
    email6 = Column(String(255), comment="メールアドレス6")
    zip_code = Column(String(255), comment="郵便番号")
    prefectures_code = Column(String(13), index=True, nullable=False, comment="住所（都道府県）")
    address1 = Column(String(255), nullable=False, comment="住所（市区町村）")
    address2 = Column(String(255), nullable=False, comment="住所（番地）")
    address3 = Column(String(255), nullable=False, comment="住所（建物名）")
    residence_type = Column(String(255), comment="住宅（種類）")
    move_in_DateTime = Column(DateTime, comment="住宅（入居日）")
    annual_income = Column(String(255), comment="年収")
    occupation = Column(String(255), comment="職種")
    organization_name = Column(String(255), comment="勤務先名")
    organization_phone_number = Column(String(255), nullable=False, comment="勤務先電話番号")
    hire_DateTime = Column(DateTime, comment="入社日")
    my_store_code = Column(String(13), comment="担当店舗")
    pet = Column(String(255), comment="ペット")
    drink = Column(String(255), comment="ドリンク")
    parents_home_address = Column(String(255), comment="実家")
    hobby = Column(String(255), comment="趣味")
    line_id = Column(String(255), comment="LINE_ID")
    optin_times_weekdays_from9 = Column(Integer, comment="案内可否平日9〜12時")
    optin_times_weekdays_from12 = Column(Integer, comment="案内可否平日12〜18時")
    optin_times_weekdays_from18 = Column(Integer, comment="案内可否平日18時以降")
    optin_times_holidays_from9 = Column(Integer, comment="案内可否土日祝9〜12時")
    optin_times_holidays_from12 = Column(Integer, comment="案内可否土日祝12〜18時")
    optin_times_holidays_from18 = Column(Integer, comment="案内可否土日祝18時以降")
    vip = Column(Integer, comment="V.I.P")

    insert_id = Column(BigInteger, nullable=False, comment="登録者")
    insert_at = Column(DateTime, nullable=False, comment="登録日時")
    upDateTime_id = Column(BigInteger, nullable=False, comment="更新者")
    upDateTime_at = Column(DateTime, nullable=False, comment="更新日時")
    delete_id = Column(BigInteger, comment="削除者")
    delete_at = Column(DateTime, default=None, comment="削除日時")
    delete_flag = Column(Integer, index=True, default=0, nullable=False, comment="削除フラグ")